---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
   name: inspec

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[test-inspec::default]
    attributes:
  - name: profile
    run_list:
      - recipe[test-inspec::profile]
